version: '3.3'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    restart: always
    volumes:
    - /dev/urandom:/dev/random:ro
    - ./data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
      JAVA_TIMEZONE: "Europe/Moscow"
    networks:
      - metanet
    secrets:
      - db_password
      - db_user
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - metanet
    secrets:
      - db_password
      - db_user

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: metabase@lipinr.ru
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - 127.0.0.1:5050:5050
    networks:
      - metanet
    secrets:
      - pgadmin_password
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: always
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log/:/var/log/nginx/:rw
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - /var/www/html/:/var/www/html/:ro
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - metanet

networks:
  metanet:
    driver: bridge
secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
  pgadmin_password:
    file: pgadmin_password.txt
